# Generated by Django 3.2.8 on 2021-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
