# Generated by Django 3.2.8 on 2021-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211121_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=()),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=()),
        ),
    ]
