# Generated by Django 3.2.8 on 2021-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211124_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
