# Generated by Django 3.2.8 on 2021-12-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211124_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='expmonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='expyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
